version: '3.8'

services:
  test_cupy:
    build: .
    image: dikorsch/cs_parts
    container_name: cs_parts-cupy_test
    user: ${UID}:${GID}
    command: python -c "import cupy as cp; print(cp.zeros(8) + 2); cp.show_config()"

    volumes:
      - ${HOME}/.cupy:/.cupy


  experiment:
    build: .
    image: dikorsch/cs_parts
    container_name: cs_parts
    user: ${UID}:${GID}

    command: ls -la

    volumes:
      - ${HOME}/.cupy:/.cupy

      - ../${SVM_TRAINING}:/code/${SVM_TRAINING}
      - ../${ESTIMATOR_FOLDER}:/code/${ESTIMATOR_FOLDER}
      - ../${EXTRACTOR_FOLDER}:/code/${EXTRACTOR_FOLDER}
    #   # mount original datasets
    #   - ${CUB200}:${CONTAINER_DATA}/original_datasets/CUB200:ro
    #   - ${BIRDSNAP}:${CONTAINER_DATA}/original_datasets/BIRDSNAP:ro
    #   - ${NAB}:${CONTAINER_DATA}/original_datasets/NAB:ro
    #   - ${FLOWERS}:${CONTAINER_DATA}/original_datasets/FLOWERS:ro
    #   - ${CARS}:${CONTAINER_DATA}/original_datasets/CARS:ro
    #   - ${HERBA19}:${CONTAINER_DATA}/original_datasets/HERBA19:ro
    #   - ${MOTHS}:${CONTAINER_DATA}/original_datasets/MOTHS:ro

    #   # mount this folder for some dataset preprocessing
    #   - ./${DATASETS_FOLDER}:${CONTAINER_DATA}/${DATASETS_FOLDER}:rw

    #   # mount models
    #   - ./${MODELS_FOLDER}:${CONTAINER_DATA}/${MODELS_FOLDER}:ro

    #   # mount output folder
    #   - ./${OUTPUT_FOLDER}:${PIPELINE_OUTPUT}:rw

    #   # mount code folder
    #   - .:${CODE_ROOT}:ro

    #   # mount repos folders
    #   - ../02_Part_Estimation:${REPOS_ROOT}/${ESTIMATOR_FOLDER}:ro
    #   - ../03_Feature_Extraction:${REPOS_ROOT}/${EXTRACTOR_FOLDER}:ro
    #   - ../04_SVM_Training:${REPOS_ROOT}/${SVM_TRAINING}:ro


    env_file:
      - .env

    # environment:
    #   - HOME=/home
    #   - PIPELINE_OUTPUT=${PIPELINE_OUTPUT}
    #   - CONTAINER_DATA=${CONTAINER_DATA}
    #   - GPU=${GPU}
    #   - DATASETS=${DATASETS}
    #   - DATASETS_FOLDER=${DATASETS_FOLDER}
    #   - BATCH_SIZE=${BATCH_SIZE}
    #   - REPOS_ROOT=${REPOS_ROOT}
    #   - CODE_ROOT=${CODE_ROOT}
