version: '2.3'

services:
  experiment:
    user: ${USER_ID}:${GROUP_ID}
    runtime: nvidia
    image: l1_parts
    build: .

    command: ${CODE_ROOT}/pipeline.sh

    volumes:
      # mount original datasets
      - ${CUB200}:${CONTAINER_DATA}/original_datasets/CUB200:ro
      - ${BIRDSNAP}:${CONTAINER_DATA}/original_datasets/BIRDSNAP:ro
      - ${NAB}:${CONTAINER_DATA}/original_datasets/NAB:ro
      - ${FLOWERS}:${CONTAINER_DATA}/original_datasets/FLOWERS:ro
      - ${CARS}:${CONTAINER_DATA}/original_datasets/CARS:ro
      - ${HERBA19}:${CONTAINER_DATA}/original_datasets/HERBA19:ro

      # mount this folder for some dataset preprocessing
      - ./${DATASETS_FOLDER}:${CONTAINER_DATA}/${DATASETS_FOLDER}:rw

      # mount models
      - ./${MODELS_FOLDER}:${CONTAINER_DATA}/${MODELS_FOLDER}:ro

      # mount output folder
      - ./${OUTPUT_FOLDER}:${PIPELINE_OUTPUT}:rw

      # mount code folder
      - .:${CODE_ROOT}:ro


    env_file:
      - .env

    environment:
      - HOME=/home
      - PIPELINE_OUTPUT=${PIPELINE_OUTPUT}
      - CONTAINER_DATA=${CONTAINER_DATA}
      - GPU=${GPU}
      - DATASETS=${DATASETS}
      - DATASETS_FOLDER=${DATASETS_FOLDER}
      - BATCH_SIZE=${BATCH_SIZE}
      - REPOS_ROOT=${REPOS_ROOT}
      - CODE_ROOT=${CODE_ROOT}
